"""add food_id to fridge table

Revision ID: 55e055cd6d98
Revises: 699b657e937e
Create Date: 2021-10-27 12:52:24.995766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e055cd6d98'
down_revision = '699b657e937e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fridge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_food_food_id_id', 'food', ['food_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fridge', schema=None) as batch_op:
        batch_op.drop_constraint('fk_food_food_id_id', type_='foreignkey')
        batch_op.drop_column('food_id')

    # ### end Alembic commands ###
