"""user_id and time in Portion

Revision ID: 5cdb7145e180
Revises: b2224335d272
Create Date: 2021-10-25 11:25:16.219085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdb7145e180'
down_revision = 'b2224335d272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_portion_time'), ['time'], unique=False)
        batch_op.create_foreign_key('fk_user_id_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('food_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_food_id_id', 'food', ['food_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_portion_time'))
        batch_op.drop_column('time')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
