"""pal in user

Revision ID: d1a0ef95d4d4
Revises: c1b50b05c972
Create Date: 2021-10-21 10:55:51.365018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a0ef95d4d4'
down_revision = 'c1b50b05c972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pal')
    # ### end Alembic commands ###
